name = "adbt"
description = "CLI tool to manage an SQlite database of acronyms."
version = "0.0.4"

authors = ["Simon Rowe"]
maintainers = ["Simon Rowe <simon@wiremoons.com>"]
maintainers-logins = ["wiremoons"]

executables = ["adbt"]
