name = "adbt"
description = "CLI tool to manage an SQlite database of acronyms."
version = "0.1.6"

authors = ["Simon Rowe"]
maintainers = ["Simon Rowe <simon@wiremoons.com>"]
maintainers-logins = ["wiremoons"]

executables = ["adbt"]

[[depends-on]]  # This line was added by `alr with`
gnatcoll_sqlite = "*"  # This line was added by `alr with`
